package com.gss.entity;

public class Collect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.collect_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Integer collectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.us_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Integer usId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.book_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Integer bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.collect_id
     *
     * @return the value of collect.collect_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getCollectId() {
        return collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.collect_id
     *
     * @param collectId the value for collect.collect_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setCollectId(Integer collectId) {
        this.collectId = collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.us_id
     *
     * @return the value of collect.us_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getUsId() {
        return usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.us_id
     *
     * @param usId the value for collect.us_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsId(Integer usId) {
        this.usId = usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.book_id
     *
     * @return the value of collect.book_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.book_id
     *
     * @param bookId the value for collect.book_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
}