package com.gss.entity;

import java.math.BigDecimal;

public class OrderItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.items_id
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    private Long itemsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.order_id
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.product_id
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.product_num
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    private BigDecimal productNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.items_id
     *
     * @return the value of order_items.items_id
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    public Long getItemsId() {
        return itemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.items_id
     *
     * @param itemsId the value for order_items.items_id
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    public void setItemsId(Long itemsId) {
        this.itemsId = itemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.order_id
     *
     * @return the value of order_items.order_id
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.order_id
     *
     * @param orderId the value for order_items.order_id
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.product_id
     *
     * @return the value of order_items.product_id
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.product_id
     *
     * @param productId the value for order_items.product_id
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.product_num
     *
     * @return the value of order_items.product_num
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    public BigDecimal getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.product_num
     *
     * @param productNum the value for order_items.product_num
     *
     * @mbggenerated Sun Apr 14 16:26:06 CST 2019
     */
    public void setProductNum(BigDecimal productNum) {
        this.productNum = productNum;
    }
}