package com.gss.entity;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productId
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productName
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.alias
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productImages
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    private String productimages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.unit
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sort
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productMassage
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    private String productmassage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.merit
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    private String merit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.recommend
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    private String recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.taboo
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    private String taboo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productId
     *
     * @return the value of product.productId
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productId
     *
     * @param productid the value for product.productId
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productName
     *
     * @return the value of product.productName
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productName
     *
     * @param productname the value for product.productName
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.alias
     *
     * @return the value of product.alias
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.alias
     *
     * @param alias the value for product.alias
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productImages
     *
     * @return the value of product.productImages
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public String getProductimages() {
        return productimages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productImages
     *
     * @param productimages the value for product.productImages
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public void setProductimages(String productimages) {
        this.productimages = productimages == null ? null : productimages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.unit
     *
     * @return the value of product.unit
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.unit
     *
     * @param unit the value for product.unit
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sort
     *
     * @return the value of product.sort
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sort
     *
     * @param sort the value for product.sort
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productMassage
     *
     * @return the value of product.productMassage
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public String getProductmassage() {
        return productmassage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productMassage
     *
     * @param productmassage the value for product.productMassage
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public void setProductmassage(String productmassage) {
        this.productmassage = productmassage == null ? null : productmassage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.merit
     *
     * @return the value of product.merit
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public String getMerit() {
        return merit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.merit
     *
     * @param merit the value for product.merit
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public void setMerit(String merit) {
        this.merit = merit == null ? null : merit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.recommend
     *
     * @return the value of product.recommend
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public String getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.recommend
     *
     * @param recommend the value for product.recommend
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public void setRecommend(String recommend) {
        this.recommend = recommend == null ? null : recommend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.taboo
     *
     * @return the value of product.taboo
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public String getTaboo() {
        return taboo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.taboo
     *
     * @param taboo the value for product.taboo
     *
     * @mbggenerated Tue Apr 09 16:34:08 CST 2019
     */
    public void setTaboo(String taboo) {
        this.taboo = taboo == null ? null : taboo.trim();
    }
}