package com.gss.entity;

public class Shopcar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.car_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.us_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private Integer usId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.productId
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.car_count
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private Integer carCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.car_id
     *
     * @return the value of shopcar.car_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.car_id
     *
     * @param carId the value for shopcar.car_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.us_id
     *
     * @return the value of shopcar.us_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Integer getUsId() {
        return usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.us_id
     *
     * @param usId the value for shopcar.us_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setUsId(Integer usId) {
        this.usId = usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.productId
     *
     * @return the value of shopcar.productId
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.productId
     *
     * @param productid the value for shopcar.productId
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.car_count
     *
     * @return the value of shopcar.car_count
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Integer getCarCount() {
        return carCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.car_count
     *
     * @param carCount the value for shopcar.car_count
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setCarCount(Integer carCount) {
        this.carCount = carCount;
    }
}