package com.gss.entity;

public class Shopcar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.car_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.us_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private Integer usId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.product_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.car_price
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private Integer carPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.car_count
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private Integer carCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.car_id
     *
     * @return the value of shopcar.car_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.car_id
     *
     * @param carId the value for shopcar.car_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.us_id
     *
     * @return the value of shopcar.us_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public Integer getUsId() {
        return usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.us_id
     *
     * @param usId the value for shopcar.us_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setUsId(Integer usId) {
        this.usId = usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.product_id
     *
     * @return the value of shopcar.product_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.product_id
     *
     * @param productId the value for shopcar.product_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.car_price
     *
     * @return the value of shopcar.car_price
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public Integer getCarPrice() {
        return carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.car_price
     *
     * @param carPrice the value for shopcar.car_price
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setCarPrice(Integer carPrice) {
        this.carPrice = carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.car_count
     *
     * @return the value of shopcar.car_count
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public Integer getCarCount() {
        return carCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.car_count
     *
     * @param carCount the value for shopcar.car_count
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setCarCount(Integer carCount) {
        this.carCount = carCount;
    }
}