package com.gss.mapper;

import com.gss.entity.Attention;
import com.gss.entity.AttentionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttentionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    int countByExample(AttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    int deleteByExample(AttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    int insert(Attention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    int insertSelective(Attention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    List<Attention> selectByExample(AttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    Attention selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") Attention record, @Param("example") AttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    int updateByExample(@Param("record") Attention record, @Param("example") AttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    int updateByPrimaryKeySelective(Attention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    int updateByPrimaryKey(Attention record);


}